# This is just a comment.
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: multi-sc
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
parameters:
  storageAccountType: Premium_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multi-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: multi-sc
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: multi-secret
data:
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-cm
data:
  foo: "42"
  image: this-is-not-a-docker-image
---
apiVersion: batch/v1
kind: Job
metadata:
  name: multi-job
spec:
  template:
    spec:
      containers:
      - name: timer
        image: ruby:3.1
        command: ["ruby", "-e", "5.times { p Process.clock_gettime(Process::CLOCK_MONOTONIC); sleep(1) }"]
      restartPolicy: Never
  backoffLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-frontend-deployment
  labels:
    app: multi-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-frontend
  template:
    metadata:
      labels:
        app: multi-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.23
        ports:
        - name: http
          containerPort: 80
      initContainers:
      - name: nginx-init
        image: busybox:1.35
        command: ["sleep", "10"]
---
apiVersion: v1
kind: Service
metadata:
  name: multi-frontend-svc
  labels:
    app: multi-frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: multi-frontend
  type: LoadBalancer
---
