name: dependabot_testcase
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.14.13 # Locked to 1.14.13, can update with no unlock.
  retry: ^2.0.0 # Can update with updated constraint, no further constraints.
  protobuf: ^2.0.0 # Can update with updated constraint, only together with fixnum.
  fixnum: ^1.1.0
  path: 1.8.1 # Already at latest
